version: "3.8"

services:
  app:
    container_name: nest-monay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    volumes:
      - .:/src
    command: npm run start:dev
    restart: always 
